=== longchass/UOW-past-courses-content/CSIT128/review/lol.xsd
<?xml version = "1.0"?>
<xsd:schema  xmlns:xsd="http://www.w3.org/2001/XMLSchema"> 
	<xsd:element name="trainlist">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="train" minOccurs="0" maxOccurs="unbounded">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="time" type="xsd:string"/>
							<xsd:element name="station" type="xsd:string"/>
							<xsd:element name="platform" type="xsd:string"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
							<xsd:attribute name="state" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>	
</xsd:schema>

=== longchass/UOW-past-courses-content/CSIT128/review/lol.xml
<?xml version="1.0" standalone="yes"?>
<!DOCTYPE trainlist[
	<!ELEMENT trainlist (train*)>
	<!ATTLIST trainlist CDATA #REQUIRED>
	<!ELEMENT train (time, station, platform)>
	<!ELEMENT time (#PCDATA)>
	<!ELEMENT station (#PCDATA)>
	<!ELEMENT platform (#PCDATA)>
]>

<trainlist state="NSW" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="lol.xsd">
	<train>
		<time>08:54</time>
		<station>Wollongong</station>
		<platform>2</platform>
	</train>
	<train>
		<time>08:56</time>
		<station>Coniston</station>
		<platform>2</platform>
	</train>
	<train>
		<time>09:01</time>
		<station>Unanderra</station>
		<platform>1</platform>
	</train>
	<train>
		<time>09:07</time>
		<station>Dapto</station>
		<platform>2</platform>
	</train>
	<train>
		<time>09:15</time>
		<station>Albion Park</station>
		<platform>2</platform>
	</train>
	<train>
		<time>09:21</time>
		<station>Oak Flats</station>
		<platform>1</platform>
	</train>
</trainlist>
